### PR TITLE
Add extensionCallBack support

### PR DESCRIPTION
**Pull request by Eathox**
Heyo, 

Arma added Extension Callback support and after some struggling I managed to get it working in go.
Since my extension is based on this template I thought I'd contribute by adding Extension Callback support.

### CODE REVIEW

**Comment by code34** [comment]
Hi @Eathox

Thank you for your pull request. 

I will check it during the next week cause i m not familiar with how BIS implemented callback function.

**Comment by code34** [comment]
hi @Eathox 

it seems to be ok cause Goland doesn't permit to call directly c function pointer.

I have to test now.

**Comment by code34** [comment]
ok nice work. I merge it to the base and will fine tune it.

**Comment by Eathox** [comment]
Cool, glad to be able to contribute.

**Pull request merged**
